# Generated by Django 4.2.5 on 2023-10-01 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='splitwise.contribution')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_user', to='user_auth.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_user', to='user_auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('type', models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent')], max_length=20)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Due',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('contribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='splitwise.contribution')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_to_user', to='user_auth.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_from_user', to='user_auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='splitwise.expense'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.user'),
        ),
    ]
