# Generated by Django 4.2.5 on 2023-10-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splitwise', '0002_alter_contribution_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='percent',
            field=models.FloatField(null=True),
        ),
    ]
